services:
  app:
    build: .
    container_name: flask_proxy_app
    restart: unless-stopped
    environment:

      TARGET_URL: https://f.mirea.ru/
      ENABLE_URL_REWRITING: true
      PYTHONUNBUFFERED: 1

  nginx:
    image: nginx:stable-alpine
    container_name: flask_proxy_nginx
    restart: unless-stopped
    ports:
      - "${PROXY_PORT:-5000}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app